# YAML configuration for two Blackfly S cameras with triggering
# Mirrors parameters from the original multiple_cameras.launch.py
cameras:
  - name: "cam_0"
    serial_number: "20435008" # Default cam_0_serial from multiple_cameras.launch.py
    camera_type: "blackfly_s"
    ros_parameters:
      debug: False
      compute_brightness: True # From multiple_cameras camera_params
      dump_node_map: False
      adjust_timestamp: True
      gain_auto: 'Off'
      gain: 0.0 # Ensure float if necessary, original was int
      exposure_auto: 'Off'
      exposure_time: 9000
      line2_selector: 'Line2'
      line2_v33enable: False # As per multiple_cameras.launch.py camera_params
      line3_selector: 'Line3'
      line3_linemode: 'Input'
      trigger_selector: 'FrameStart'
      trigger_mode: 'On'
      trigger_source: 'Line3'
      trigger_delay: 9.0 # Ensure float if necessary, original was int
      trigger_overlap: 'ReadOut'
      chunk_mode_active: True
      chunk_selector_frame_id: 'FrameID'
      chunk_enable_frame_id: True
      chunk_selector_exposure_time: 'ExposureTime'
      chunk_enable_exposure_time: True
      chunk_selector_gain: 'Gain'
      chunk_enable_gain: True
      chunk_selector_timestamp: 'Timestamp'
      chunk_enable_timestamp: True
  - name: "cam_1"
    serial_number: "20415937" # Default cam_1_serial from multiple_cameras.launch.py
    camera_type: "blackfly_s"
    ros_parameters:
      # Using the same parameters as cam_0 for consistency with original multiple_cameras.launch.py
      debug: False
      compute_brightness: True
      dump_node_map: False
      adjust_timestamp: True
      gain_auto: 'Off'
      gain: 0.0 # Ensure float
      exposure_auto: 'Off'
      exposure_time: 9000
      line2_selector: 'Line2'
      line2_v33enable: False
      line3_selector: 'Line3'
      line3_linemode: 'Input'
      trigger_selector: 'FrameStart'
      trigger_mode: 'On'
      trigger_source: 'Line3'
      trigger_delay: 9.0 # Ensure float
      trigger_overlap: 'ReadOut'
      chunk_mode_active: True
      chunk_selector_frame_id: 'FrameID'
      chunk_enable_frame_id: True
      chunk_selector_exposure_time: 'ExposureTime'
      chunk_enable_exposure_time: True
      chunk_selector_gain: 'Gain'
      chunk_enable_gain: True
      chunk_selector_timestamp: 'Timestamp'
      chunk_enable_timestamp: True
