# YAML configuration for a single Blackfly S camera
# Mirrors parameters from the original driver_node.launch.py example_parameters['blackfly_s']
cameras:
  - name: "flir_camera"
    serial_number: "20435008" # Default serial from driver_node.launch.py
    camera_type: "blackfly_s"
    # parameter_file: "" # Explicitly empty or commented out to use default spinnaker_camera_driver config
    ros_parameters:
      debug: False
      compute_brightness: False
      adjust_timestamp: True
      dump_node_map: False
      gain_auto: 'Continuous'
      exposure_auto: 'Continuous'
      frame_rate_auto: 'Off'
      frame_rate: 40.0
      frame_rate_enable: True
      buffer_queue_size: 10
      trigger_mode: 'Off'
      chunk_mode_active: True
      chunk_selector_frame_id: 'FrameID'
      chunk_enable_frame_id: True
      chunk_selector_exposure_time: 'ExposureTime'
      chunk_enable_exposure_time: True
      chunk_selector_gain: 'Gain'
      chunk_enable_gain: True
      chunk_selector_timestamp: 'Timestamp'
      chunk_enable_timestamp: True
      # For GigE cameras, if applicable for a specific blackfly_s model, these might be needed:
      # device_link_throughput_limit: 380000000
      # gev_scps_packet_size: 9000
      # For specific image ROI settings, if needed:
      # image_width: 1408
      # image_height: 1080
      # offset_x: 16
      # offset_y: 0
