camera_config:
  cameras:
    - serial: "17301966"
      name: "front_left"
      framerate: 30.0
      exposure: 9996.41
      gain: 18.4 
      role: "solo"
      video_mode: "Mode2"
    - serial: "17301975"
      name: "front_right"
      framerate: 30.0
      exposure: 9996.41
      gain: 18.4 
      role: "solo"
      video_mode: "Mode2"