camera_config:
  cameras:
    - serial: "_"
      name: "front_left"
      framerate: 30.0
      width: 1280
      height: 720
      sync: primary
    - serial: "_"
      name: "front_right"
      framerate: 30.0
      width: 1280
      height: 720
      sync: secondary
